language: python
os:
  - linux
python:
  - "3.5"
  - "3.6"
  - "pypy3.5"

matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
install:
  - echo 
script:
  - python test.py