language: python

matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7
      dist: xenial
    - name: "PyPy 3.5 on Xenial Linux"
      python: "pypy3.5"
      dist: xenial

    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
install:
  - echo 
script:
  - python3 test.py || python test.py